modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="createcomputerextended"
version="0.1.0"
displayName="Create Computer Extended"
description="Network gearbox + CC integration mod"

[[mixins]]
config="createcomputerextended.mixins.json"