modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="createcomputerextended"
version="1.0.0"
displayName="Create Computer Extended"
description="Network gearbox + CC integration mod"